name: typeset

on:
  push:
    branches:
      - main

env:
  target-tex-source: sample.tex

jobs:
  compile-LaTeX-to-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 5 # timeout upper bounds

    ## workflow
    steps:
      # fork into github workstation vm
      - name: Checkout
        uses: actions/checkout@v4

      # finalize
      - name: Get Current Date String
        if: success()
        id: date
        run: |
          echo "date=$(TZ=TIME_ZONE date +'%Y%m%d')" >$GITHUB_OUTPUT
      - name: Get Counter String
        id: counter
        if: success()
        run: |
          LAST_RELEASE=$(gh release view --json=tagName | jq -r '.tagName')
          LAST_DATE=$(echo $LAST_RELEASE|sed 's/-.*$//')
          LAST_COUNTER=$(echo $LAST_RELEASE|sed 's/.*-//')
          if [ "$LAST_DATE" = "$DATE" ]
          then
            echo "counter=$(($LAST_COUNTER +1))" >$GITHUB_OUTPUT
          else
            echo "counter=1" >$GITHUB_OUTPUT
          fi
        env:
          DATE: ${{ steps.date.outputs.date }}
          GH_TOKEN: ${{ github.token }}
          TIME_ZONE: JST-9 # Specify time zone here
      - name: Get Repository String
        if: success()
        id: repository
        run: |
          echo "repository=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      - name: Get Full Version String
        if: success()
        id: fullversion
        run: |
          echo "version=${{ steps.repository.outputs.repository }}-${{ steps.date.outputs.date }}-${{ steps.counter.outputs.counter }}" >$GITHUB_OUTPUT
      - name: Get Short Version String
        if: success()
        id: shortversion
        run: |
          echo "version=${{ steps.date.outputs.date }}-${{ steps.counter.outputs.counter }}" >$GITHUB_OUTPUT
      - name: Debug String
        run: |
          echo ${{ steps.repository.outputs.repository }}
          echo ${{ steps.date.outputs.date }}
          echo ${{ steps.counter.outputs.counter }}
          echo ${{ steps.shortversion.outputs.version }}
          echo ${{ steps.fullversion.outputs.version }}

      # compile
      - name: Compile LaTeX Document
        if: success()
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.target-tex-source }}
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -jobname=${{ steps.fullversion.outputs.version }}

      # export pdf
      - name: Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.shortversion.outputs.version }}
          tag_name: ${{ steps.shortversion.outputs.version }}
          files: |
            out/${{ steps.fullversion.outputs.version }}.pdf
            .LICENSE