name: typeset
on:
  push:
    branches:
      - main

jobs:
  release-pdf:
    ## action-gh-release dependency
    permissions:
      contents: write
    ## ToDo: version building
    runs-on: ubuntu-latest
    ## workflow
    steps:
      # fork into github workstation vm
      - name: Checkout
        uses: actions/checkout@v4
      # finalize
      - name: Get Current Date String
        id: date
        run: |
          echo "date=$(TZ=TIME_ZONE date +'%Y%m%d')" >$GITHUB_OUTPUT
      - name: Get Counter String
        id: counter
        run: |
          LAST_RELEASE=$(gh release view --json=tagName | jq -r '.tagName')
          LAST_DATE=$(echo $LAST_RELEASE|sed 's/-.*$//')
          LAST_COUNTER=$(echo $LAST_RELEASE|sed 's/.*-//')
          if [ "$LAST_DATE" = "$DATE" ]
          then
            echo "counter=$(($LAST_COUNTER +1))" >$GITHUB_OUTPUT
          else
            echo "counter=1" >$GITHUB_OUTPUT
          fi
        env:
          DATE: ${{ steps.date.outputs.date }}
          GH_TOKEN: ${{ github.token }}
          TIME_ZONE: JST-9 # Specify time zone here
      - name: Get Repository String
        id: repository
        run: |
          echo "repository=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      - name: Get Version String
        if: success()
        id: version
        run: |
          echo "version=${{ steps.repository.outputs.repository }}-${{ steps.date.outputs.date }}-${{ steps.counter.outputs.counter }}" >$GITHUB_OUTPUT
      - name: debug string
        run: |
          echo ${{ steps.repository.outputs.repository }}
          echo ${{ steps.date.outputs.date }}
          echo ${{ steps.counter.outputs.counter }}
          echo ${{ steps.version.outputs.version }}

      # compile
      - name: compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sample.tex
      - name: convert release PDF filename
        run: mv out/sample.pdf out/${{ steps.version.outputs.version }}.pdf
      # export pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          files: |
            out/${{ steps.version.outputs.version }}.pdf
            LICENSE