name: typeset
on:
  push:
    branches:
      - main

jobs:
  release-pdf:
    ## ToDo: version building
    runs-on: ubuntu-latest
    ## workflow
    steps:
      # fork into github workstation vm
      - name: checkout
        uses: actions/checkout@v4
      # compile
      - name: compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sample.tex
      # export pdf
      #- name: Upload PDF file
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: PDF
      #    path: out/sample.pdf
      - name: test
        run: ls -l out/sample.pdf LICENSE
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/sample.pdf
            LICENSE