name: typeset
on:
  push:
    branches:
      - main

jobs:
  release-pdf:
    ## action-gh-release dependency
    permissions:
      contents: write
    ## ToDo: version building
    runs-on: ubuntu-latest
    ## workflow
    steps:
      # fork into github workstation vm
      - name: checkout
        uses: actions/checkout@v4
      # compile
      - name: compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sample.tex
      # export pdf
      #- name: Upload PDF file
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: PDF
      #    path: out/sample.pdf
      - name: test
        run: ls -l out/sample.pdf LICENSE
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: action-gh-test
          files: |
            out/sample.pdf
            LICENSE